### ISSUE TITLE
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported

### ISSUE THREAD

**Issue by davidbrochart** [DavidBuchanan314/pyswargol#2]
Great blog post!
I wanted to try this out, but I get this error (on Ubuntu 22.04/x86_64):
```
Config: LifeConfig(width=1280, height=720, vsync=True, fullscreen=False, drylife=True, slow=False, frameskip=1, num_procs=8, bench_frames=0)
Exception in thread Thread-2 (blit_thread):
Traceback (most recent call last):
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/david/tmp/pyswargol/swargol.py", line 251, in blit_thread
    raise Exception("SDL_ConvertSurfaceFormat: " + sdl2.SDL_GetError().decode())
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported
Exception in thread Thread-1 (blit_thread):
Traceback (most recent call last):
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/david/tmp/pyswargol/swargol.py", line 251, in blit_thread
    raise Exception("SDL_ConvertSurfaceFormat: " + sdl2.SDL_GetError().decode())
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported
Exception in thread Thread-3 (blit_thread):
Traceback (most recent call last):
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/david/tmp/pyswargol/swargol.py", line 251, in blit_thread
    raise Exception("SDL_ConvertSurfaceFormat: " + sdl2.SDL_GetError().decode())
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported
Exception in thread Thread-4 (blit_thread):
Traceback (most recent call last):
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1010, in run
Exception in thread Thread-5 (blit_thread):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/home/david/tmp/pyswargol/swargol.py", line 251, in blit_thread
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    raise Exception("SDL_ConvertSurfaceFormat: " + sdl2.SDL_GetError().decode())
    self.run()
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1010, in run
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported
Exception in thread Thread-8 (blit_thread):
Exception in thread Thread-6 (blit_thread):
Traceback (most recent call last):
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/david/tmp/pyswargol/swargol.py", line 251, in blit_thread
Exception in thread Thread-7 (blit_thread):
Traceback (most recent call last):
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    raise Exception("SDL_ConvertSurfaceFormat: " + sdl2.SDL_GetError().decode())
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1010, in run
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1010, in run
  File "/home/david/tmp/pyswargol/swargol.py", line 251, in blit_thread
    self._target(*self._args, **self._kwargs)
  File "/home/david/tmp/pyswargol/swargol.py", line 251, in blit_thread
    raise Exception("SDL_ConvertSurfaceFormat: " + sdl2.SDL_GetError().decode())
    raise Exception("SDL_ConvertSurfaceFormat: " + sdl2.SDL_GetError().decode())
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported
Traceback (most recent call last):
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/david/tmp/pyswargol/.pixi/env/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/david/tmp/pyswargol/swargol.py", line 251, in blit_thread
    raise Exception("SDL_ConvertSurfaceFormat: " + sdl2.SDL_GetError().decode())
Exception: SDL_ConvertSurfaceFormat: Blit combination not supported
```

**Comment by DavidBuchanan314** [comment]
Unfortunately Ubuntu ships a rather outdated SDL2, and blitting 4-bit surfaces is a relatively recent feature - I don't know which version it was added in specifically

**Comment by DavidBuchanan314** [comment]
I think this is the PR that added it: https://github.com/libsdl-org/SDL/pull/8573

Ah no that just improved it, this might be the introductory commit https://github.com/libsdl-org/SDL/commit/a75041e8dd820b89e746c737f58d0163e100a3e6 , which I think first appeared in release version 2.0.22

**Comment by davidbrochart** [comment]
Actually I use conda-forge so the fix was as simple as `pixi add sdl2`.
Works like a charm, thanks!
