### ISSUE TITLE
SDL Issue

### ISSUE THREAD

**Issue by qtndm** [DavidBuchanan314/pyswargol#3]
Hello, I installed sdl etc but when i launch the program it says me this : 

Traceback (most recent call last):
  File "C:\Users\nayth\PycharmProjects\pyswargol\swargol.py", line 444, in <module>
    main(cfg)
  File "C:\Users\nayth\PycharmProjects\pyswargol\swargol.py", line 363, in main
    raise Exception("Failed to init SDL2")
Exception: Failed to init SDL2

Do you have any idea on how to fix this ? Thank you for your help.

**Comment by DavidBuchanan314** [comment]
I'd recommend raising this issue with the pysdl2 devs https://github.com/py-sdl/py-sdl2

**Comment by diimdeep** [comment]
Fixed for me on macos https://github.com/DavidBuchanan314/pyswargol/blob/bb8a748065bbe6f7a1c0bf4a331b42e178e9d821/swargol.py#L51

```
import sys
if sys.platform.startswith('linux'): os.environ["SDL_VIDEODRIVER"] = "x11"
```
